### ISSUE TITLE
The Big Issue

### ISSUE THREAD

**Issue by maustingit** [greenpeace/open-learning#11]
Just following bread crumbs to see where they lead ...

**Comment by gyaresu** [comment]
Top of the morning to you @maustingit 

Can you tell us a little about yourself?

**Comment by maustingit** [comment]
Hey - just a dude sitting upstairs at GPI, quietly sending emails to the GPI email list and occasionally trying to figure out how to edit java script on campaigns in Engaging Networks (if I stare at it long enough and test 101 iterations, I can usually successfully edit java script, but I haven't advanced too far beyond designing emails using basic HTML). 

So perhaps this is an opportunity to broaden my horizons and maybe get some coding parkour skills.

**Comment by gyaresu** [comment]
aaaaaah... m austin git

Got it :+1: 

Then might I suggest to you sir that perhaps you create a folder here and save some of those Javascript snippets in it? Perhaps it's something we can help debug?

**Comment by gyaresu** [comment]
TODO: #15
