### ISSUE TITLE
Issues? You bet I have issues... 

### ISSUE THREAD

**Issue by Brianfit** [greenpeace/open-learning#14]
When humans discovered all of this underground kidnapped carbon, you have to remember that for them, the carbon wasn’t the point. They were staring at an endless sea of 300 million-year-old, densely packed sunshine—trillions of ancient plants with their joules intact—and since there are no laws protecting the estates of Carboniferous plants, we could seize it all for ourselves. The grandest joule theft in history.

**Comment by gyaresu** [comment]
# The grandest joule theft in history

Welcome @Brianfit you'll fit in just fine!

**Comment by gyaresu** [comment]
TODO: #15
