### ISSUE TITLE
While attempting to publish a Branch created with GitHub on Mac

### ISSUE THREAD

**Issue by Brianfit** [greenpeace/open-learning#20]
O h CrAp I BrokE iT 

¸.·´¯`·.´¯`·.¸¸.·´¯`·.¸><(((x>

![screen shot 2015-06-04 at 17 10 02](https://cloud.githubusercontent.com/assets/3415783/7987261/b238930e-0adc-11e5-80a7-858fbeb3ca82.jpg)

**Comment by gyaresu** [comment]
Well played sir. Well played.

Close > Open?

It’s permissions so if that doesn’t work go Preferences in the Github App and reconnect your account.

## 

Gareth

Crypto: https://keybase.io/gyaresu

**Comment by Brianfit** [comment]
Closed > Opened.
Signed out, Logged in in the app. 
Deleted Branch
Redownloaded repository
Logged in via Safari
Reviewed steps to make sure I didn't miss one
Still gots no permissions: same error message on pushing publish button on a newly created branch. 
:warning: :alien: :warning:

**Comment by gyaresu** [comment]
**THAT IS SO ANNOYING**

I do notice however that you haven't accepted the invite to the team. 

I reckon that's it. Check your inbox. I'll recheck that I didn't send it to the wrong account.

![screenshot 2015-06-04 08 47 59](https://cloud.githubusercontent.com/assets/29263/7988087/6e437894-0a96-11e5-8889-48d896d873af.png)

reference: [Permission levels for an Organisational repository](https://help.github.com/articles/permission-levels-for-an-organization-repository/)

**Comment by Brianfit** [comment]
Yeah, I don't see an invite to the team in my inbox, nor in the history of notifications. I, annoyingly, have a capital B in my user name: Brianfit. I swear, it was some autocapitalization or autocorrect bot somewhere did that to me I'm a VICTIM I'm tellin' ya: I'm a card-carrying consistent-caseist of the Unix school, drummed into me hard by one Sjoerd Jongens many many many IT Departments ago.

=( :c(|)

![screen shot 2015-06-05 at 15 09 06](https://cloud.githubusercontent.com/assets/3415783/8006509/ee97a232-0b94-11e5-8d91-bd10d80dd0ab.jpg)

**Comment by gyaresu** [comment]
Invitation resent. Unix membershitp _**revoked**_ :neckbeard: 

![screenshot 2015-06-05 08 20 39](https://cloud.githubusercontent.com/assets/29263/8009213/fa808610-0b5b-11e5-83a8-83db1f650b19.png)

![screenshot 2015-06-05 08 17 58](https://cloud.githubusercontent.com/assets/29263/8009152/7ca5ad1a-0b5b-11e5-935b-7579d8191910.png)

**Comment by Brianfit** [comment]
HooRaY! It's aLivE!
![its alive](https://cloud.githubusercontent.com/assets/3415783/8018683/d1d8a170-0c28-11e5-8a50-2a784f03dd7f.gif)
