### ISSUE TITLE
Who's maintaining GP org here? I need to invite nickofnz (Nick Young) to GP org.

### ISSUE THREAD

**Issue by datawebbie** [greenpeace/open-learning#48]
I've also created a team called "GPNZ" I'll be adding more people to that team (and to GP org) so would like to know who is the main contact person here.

Thanks!!!

**Comment by flow7** [comment]
you might have to talk to @gyaresu

**Comment by javian** [comment]
he's no longer around and associated with Greenpeace afaik. There are a few GP owners like @stripthis , @tottaz , @weremoose , @tolen and @yooster . You can check the full list here https://github.com/orgs/greenpeace/people?utf8=%E2%9C%93&query=role%3Aowner+

**Comment by gyaresu** [comment]
Actually I'm at the investigations/ action-tech skillshares right now and I've been working on GP projects all year as a specialist :)

Happy to help though, just really packed days at the moment. 

/me waves at lovely humans

**Comment by datawebbie** [comment]
Hi Gareth, actually someone already gave Nick the access. closing this ticket.

**Comment by javian** [comment]
@gyaresu I'm just not used to you being so quiet =) thanks for clearing that up.
