### ISSUE TITLE
Hello Greenpeacers

### ISSUE THREAD

**Issue by manojhl** [greenpeace/open-learning#7]
:tada: Hi all,

I'm Manoj H L, web consultant @ Greenpeace India.

It's nice to be here
:+1: :clap:

**Comment by gyaresu** [comment]
Dude! So quick! Hi!

**Comment by manojhl** [comment]
what to do.. got excited with your email!! :laughing:

**Comment by gyaresu** [comment]
Hey we should leave the issues open to start with so any new folks can see them. What do you think?

**Comment by manojhl** [comment]
Your wish..

On Thu, Jun 4, 2015 at 10:20 AM, Gareth notifications@github.com wrote:

> Hey we should leave the issues open to start with so any new folks can see
> them. What do you think?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/greenpeace/open-learning/issues/7#issuecomment-108720639
> .

## 

Manoj H L
Freelancer
Web Developer @ Greenpeace India Society

**Comment by gyaresu** [comment]
So what are you working on at the mighty Indian office?

**Comment by manojhl** [comment]
Right now I'm working on a Photo booth project for world environment day!!

**Comment by gyaresu** [comment]
A physical booth that takes pictures and then puts them on a website?

**Comment by manojhl** [comment]
:laughing: lol [It](http://www.greenpeace.in/test/photo-booth-v2/) takes picture from webcam(javascript based).

**Comment by gyaresu** [comment]
Nice! Are you using node?

**Comment by manojhl** [comment]
Nope, we don't use javascript on server side. we are bound to PHP, but
personally I like io.js than node.js.

On Thu, Jun 4, 2015 at 10:27 AM, Gareth notifications@github.com wrote:

> Nice! Are you using node?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/greenpeace/open-learning/issues/7#issuecomment-108721799
> .

## 

Manoj H L
Freelancer
Web Developer @ Greenpeace India Society

**Comment by gyaresu** [comment]
Well you'll like it even more that they're now merging under the Node Foundation: https://github.com/nodejs/io.js/issues/978

Anyway, I won't scare the new folks off with Javascript talk just yet ;)

Welcome :+1:

**Comment by manojhl** [comment]
I'm in love with :heart: JavaScript!! :cupid:  :kissing:

**Comment by smhick** [comment]
id be keen to see the photoboth project
could be an interesting project for open boat tours
